### ISSUE TITLE
Escape Mappings with Special Chars

### ISSUE THREAD

**Issue by GBwandersoncamargo** [wandersonwhcr/vim-yamlpath#8]
```yaml
metadata:
  annotations:
    meta.helm.sh/release-name: application
```

outputs `.metadata.annotations.meta.helm.sh/release-name`

must output `.metadata.annotations["meta.helm.sh/release-name"]`
